language: cpp
sudo: required

dist: trusty
compiler: gcc
os: linux

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
          - libsdl2-dev
          - libegl1-mesa-dev
          - libgles2-mesa-dev
          - libsdl2-image-dev
          - libsdl2-ttf-dev
          - libsdl2-mixer-dev
          - libsdl2-net-dev
          - libglew-dev
          - libglm-dev
          - freeglut3-dev
          - libassimp-dev

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - wget https://lukemontalvo.us/BasicEventEngine/resources.tar.gz
  - tar xzf resources.tar.gz
script: ./build.sh norun
after_success:
  - ./build/BEE_Example --single-run --headless
